export interface CountryCodeType {
  country: {
    name: string;
    isoCode: string;
  };
  dialCode: number;
}

export const countryCodes: CountryCodeType[] = [
  { dialCode: 93, country: { name: 'Afghanistan', isoCode: 'AF' } },
  { dialCode: 358, country: { name: 'Aland Islands', isoCode: 'AX' } },
  { dialCode: 355, country: { name: 'Albania', isoCode: 'AL' } },
  { dialCode: 213, country: { name: 'Algeria', isoCode: 'DZ' } },
  { dialCode: 1684, country: { name: 'AmericanSamoa', isoCode: 'AS' } },
  { dialCode: 376, country: { name: 'Andorra', isoCode: 'AD' } },
  { dialCode: 244, country: { name: 'Angola', isoCode: 'AO' } },
  { dialCode: 1264, country: { name: 'Anguilla', isoCode: 'AI' } },
  { dialCode: 672, country: { name: 'Antarctica', isoCode: 'AQ' } },
  { dialCode: 1268, country: { name: 'Antigua and Barbuda', isoCode: 'AG' } },
  { dialCode: 54, country: { name: 'Argentina', isoCode: 'AR' } },
  { dialCode: 374, country: { name: 'Armenia', isoCode: 'AM' } },
  { dialCode: 297, country: { name: 'Aruba', isoCode: 'AW' } },
  { dialCode: 247, country: { name: 'Ascension Island', isoCode: 'AC' } },
  { dialCode: 61, country: { name: 'Australia', isoCode: 'AU' } },
  { dialCode: 43, country: { name: 'Austria', isoCode: 'AT' } },
  { dialCode: 994, country: { name: 'Azerbaijan', isoCode: 'AZ' } },
  { dialCode: 1242, country: { name: 'Bahamas', isoCode: 'BS' } },
  { dialCode: 973, country: { name: 'Bahrain', isoCode: 'BH' } },
  { dialCode: 880, country: { name: 'Bangladesh', isoCode: 'BD' } },
  { dialCode: 1246, country: { name: 'Barbados', isoCode: 'BB' } },
  { dialCode: 375, country: { name: 'Belarus', isoCode: 'BY' } },
  { dialCode: 32, country: { name: 'Belgium', isoCode: 'BE' } },
  { dialCode: 501, country: { name: 'Belize', isoCode: 'BZ' } },
  { dialCode: 229, country: { name: 'Benin', isoCode: 'BJ' } },
  { dialCode: 1441, country: { name: 'Bermuda', isoCode: 'BM' } },
  { dialCode: 975, country: { name: 'Bhutan', isoCode: 'BT' } },
  { dialCode: 591, country: { name: 'Bolivia', isoCode: 'BO' } },
  { dialCode: 387, country: { name: 'Bosnia and Herzegovina', isoCode: 'BA' } },
  { dialCode: 267, country: { name: 'Botswana', isoCode: 'BW' } },
  { dialCode: 55, country: { name: 'Brazil', isoCode: 'BR' } },
  {
    dialCode: 246,
    country: { name: 'British Indian Ocean Territory', isoCode: 'IO' },
  },
  { dialCode: 673, country: { name: 'Brunei Darussalam', isoCode: 'BN' } },
  { dialCode: 359, country: { name: 'Bulgaria', isoCode: 'BG' } },
  { dialCode: 226, country: { name: 'Burkina Faso', isoCode: 'BF' } },
  { dialCode: 257, country: { name: 'Burundi', isoCode: 'BI' } },
  { dialCode: 855, country: { name: 'Cambodia', isoCode: 'KH' } },
  { dialCode: 237, country: { name: 'Cameroon', isoCode: 'CM' } },
  { dialCode: 1, country: { name: 'Canada', isoCode: 'CA' } },
  { dialCode: 238, country: { name: 'Cape Verde', isoCode: 'CV' } },
  { dialCode: 1345, country: { name: 'Cayman Islands', isoCode: 'KY' } },
  {
    dialCode: 236,
    country: { name: 'Central African Republic', isoCode: 'CF' },
  },
  { dialCode: 235, country: { name: 'Chad', isoCode: 'TD' } },
  { dialCode: 56, country: { name: 'Chile', isoCode: 'CL' } },
  { dialCode: 86, country: { name: 'China', isoCode: 'CN' } },
  { dialCode: 61, country: { name: 'Christmas Island', isoCode: 'CX' } },
  { dialCode: 61, country: { name: 'Cocos (Keeling) Islands', isoCode: 'CC' } },
  { dialCode: 57, country: { name: 'Colombia', isoCode: 'CO' } },
  { dialCode: 269, country: { name: 'Comoros', isoCode: 'KM' } },
  { dialCode: 242, country: { name: 'Congo', isoCode: 'CG' } },
  { dialCode: 682, country: { name: 'Cook Islands', isoCode: 'CK' } },
  { dialCode: 506, country: { name: 'Costa Rica', isoCode: 'CR' } },
  { dialCode: 385, country: { name: 'Croatia', isoCode: 'HR' } },
  { dialCode: 53, country: { name: 'Cuba', isoCode: 'CU' } },
  { dialCode: 357, country: { name: 'Cyprus', isoCode: 'CY' } },
  { dialCode: 420, country: { name: 'Czech Republic', isoCode: 'CZ' } },
  {
    dialCode: 243,
    country: { name: 'Democratic Republic of the Congo', isoCode: 'CD' },
  },
  { dialCode: 45, country: { name: 'Denmark', isoCode: 'DK' } },
  { dialCode: 253, country: { name: 'Djibouti', isoCode: 'DJ' } },
  { dialCode: 1767, country: { name: 'Dominica', isoCode: 'DM' } },
  { dialCode: 1849, country: { name: 'Dominican Republic', isoCode: 'DO' } },
  { dialCode: 593, country: { name: 'Ecuador', isoCode: 'EC' } },
  { dialCode: 20, country: { name: 'Egypt', isoCode: 'EG' } },
  { dialCode: 503, country: { name: 'El Salvador', isoCode: 'SV' } },
  { dialCode: 240, country: { name: 'Equatorial Guinea', isoCode: 'GQ' } },
  { dialCode: 291, country: { name: 'Eritrea', isoCode: 'ER' } },
  { dialCode: 372, country: { name: 'Estonia', isoCode: 'EE' } },
  { dialCode: 268, country: { name: 'Eswatini', isoCode: 'SZ' } },
  { dialCode: 251, country: { name: 'Ethiopia', isoCode: 'ET' } },
  {
    dialCode: 500,
    country: { name: 'Falkland Islands (Malvinas)', isoCode: 'FK' },
  },
  { dialCode: 298, country: { name: 'Faroe Islands', isoCode: 'FO' } },
  { dialCode: 679, country: { name: 'Fiji', isoCode: 'FJ' } },
  { dialCode: 358, country: { name: 'Finland', isoCode: 'FI' } },
  { dialCode: 33, country: { name: 'France', isoCode: 'FR' } },
  { dialCode: 594, country: { name: 'French Guiana', isoCode: 'GF' } },
  { dialCode: 689, country: { name: 'French Polynesia', isoCode: 'PF' } },
  { dialCode: 241, country: { name: 'Gabon', isoCode: 'GA' } },
  { dialCode: 220, country: { name: 'Gambia', isoCode: 'GM' } },
  { dialCode: 995, country: { name: 'Georgia', isoCode: 'GE' } },
  { dialCode: 49, country: { name: 'Germany', isoCode: 'DE' } },
  { dialCode: 233, country: { name: 'Ghana', isoCode: 'GH' } },
  { dialCode: 350, country: { name: 'Gibraltar', isoCode: 'GI' } },
  { dialCode: 30, country: { name: 'Greece', isoCode: 'GR' } },
  { dialCode: 299, country: { name: 'Greenland', isoCode: 'GL' } },
  { dialCode: 1473, country: { name: 'Grenada', isoCode: 'GD' } },
  { dialCode: 590, country: { name: 'Guadeloupe', isoCode: 'GP' } },
  { dialCode: 1671, country: { name: 'Guam', isoCode: 'GU' } },
  { dialCode: 502, country: { name: 'Guatemala', isoCode: 'GT' } },
  { dialCode: 44, country: { name: 'Guernsey', isoCode: 'GG' } },
  { dialCode: 224, country: { name: 'Guinea', isoCode: 'GN' } },
  { dialCode: 245, country: { name: 'Guinea-Bissau', isoCode: 'GW' } },
  { dialCode: 592, country: { name: 'Guyana', isoCode: 'GY' } },
  { dialCode: 509, country: { name: 'Haiti', isoCode: 'HT' } },
  {
    dialCode: 379,
    country: { name: 'Holy See (Vatican City State)', isoCode: 'VA' },
  },
  { dialCode: 504, country: { name: 'Honduras', isoCode: 'HN' } },
  { dialCode: 852, country: { name: 'Hong Kong', isoCode: 'HK' } },
  { dialCode: 36, country: { name: 'Hungary', isoCode: 'HU' } },
  { dialCode: 354, country: { name: 'Iceland', isoCode: 'IS' } },
  { dialCode: 91, country: { name: 'India', isoCode: 'IN' } },
  { dialCode: 62, country: { name: 'Indonesia', isoCode: 'ID' } },
  { dialCode: 98, country: { name: 'Iran', isoCode: 'IR' } },
  { dialCode: 964, country: { name: 'Iraq', isoCode: 'IQ' } },
  { dialCode: 353, country: { name: 'Ireland', isoCode: 'IE' } },
  { dialCode: 44, country: { name: 'Isle of Man', isoCode: 'IM' } },
  { dialCode: 972, country: { name: 'Israel', isoCode: 'IL' } },
  { dialCode: 39, country: { name: 'Italy', isoCode: 'IT' } },
  {
    dialCode: 225,
    country: { name: "Ivory Coast / Cote d'Ivoire", isoCode: 'CI' },
  },
  { dialCode: 1876, country: { name: 'Jamaica', isoCode: 'JM' } },
  { dialCode: 81, country: { name: 'Japan', isoCode: 'JP' } },
  { dialCode: 44, country: { name: 'Jersey', isoCode: 'JE' } },
  { dialCode: 962, country: { name: 'Jordan', isoCode: 'JO' } },
  { dialCode: 77, country: { name: 'Kazakhstan', isoCode: 'KZ' } },
  { dialCode: 254, country: { name: 'Kenya', isoCode: 'KE' } },
  { dialCode: 686, country: { name: 'Kiribati', isoCode: 'KI' } },
  {
    dialCode: 850,
    country: {
      name: "Korea, Democratic People's Republic of Korea",
      isoCode: 'KP',
    },
  },
  {
    dialCode: 82,
    country: { name: 'Korea, Republic of South Korea', isoCode: 'KR' },
  },
  { dialCode: 383, country: { name: 'Kosovo', isoCode: 'XK' } },
  { dialCode: 965, country: { name: 'Kuwait', isoCode: 'KW' } },
  { dialCode: 996, country: { name: 'Kyrgyzstan', isoCode: 'KG' } },
  { dialCode: 856, country: { name: 'Laos', isoCode: 'LA' } },
  { dialCode: 371, country: { name: 'Latvia', isoCode: 'LV' } },
  { dialCode: 961, country: { name: 'Lebanon', isoCode: 'LB' } },
  { dialCode: 266, country: { name: 'Lesotho', isoCode: 'LS' } },
  { dialCode: 231, country: { name: 'Liberia', isoCode: 'LR' } },
  { dialCode: 218, country: { name: 'Libya', isoCode: 'LY' } },
  { dialCode: 423, country: { name: 'Liechtenstein', isoCode: 'LI' } },
  { dialCode: 370, country: { name: 'Lithuania', isoCode: 'LT' } },
  { dialCode: 352, country: { name: 'Luxembourg', isoCode: 'LU' } },
  { dialCode: 853, country: { name: 'Macau', isoCode: 'MO' } },
  { dialCode: 261, country: { name: 'Madagascar', isoCode: 'MG' } },
  { dialCode: 265, country: { name: 'Malawi', isoCode: 'MW' } },
  { dialCode: 60, country: { name: 'Malaysia', isoCode: 'MY' } },
  { dialCode: 960, country: { name: 'Maldives', isoCode: 'MV' } },
  { dialCode: 223, country: { name: 'Mali', isoCode: 'ML' } },
  { dialCode: 356, country: { name: 'Malta', isoCode: 'MT' } },
  { dialCode: 692, country: { name: 'Marshall Islands', isoCode: 'MH' } },
  { dialCode: 596, country: { name: 'Martinique', isoCode: 'MQ' } },
  { dialCode: 222, country: { name: 'Mauritania', isoCode: 'MR' } },
  { dialCode: 230, country: { name: 'Mauritius', isoCode: 'MU' } },
  { dialCode: 262, country: { name: 'Mayotte', isoCode: 'YT' } },
  { dialCode: 52, country: { name: 'Mexico', isoCode: 'MX' } },
  {
    dialCode: 691,
    country: {
      name: 'Micronesia, Federated States of Micronesia',
      isoCode: 'FM',
    },
  },
  { dialCode: 373, country: { name: 'Moldova', isoCode: 'MD' } },
  { dialCode: 377, country: { name: 'Monaco', isoCode: 'MC' } },
  { dialCode: 976, country: { name: 'Mongolia', isoCode: 'MN' } },
  { dialCode: 382, country: { name: 'Montenegro', isoCode: 'ME' } },
  { dialCode: 1664, country: { name: 'Montserrat', isoCode: 'MS' } },
  { dialCode: 212, country: { name: 'Morocco', isoCode: 'MA' } },
  { dialCode: 258, country: { name: 'Mozambique', isoCode: 'MZ' } },
  { dialCode: 95, country: { name: 'Myanmar', isoCode: 'MM' } },
  { dialCode: 264, country: { name: 'Namibia', isoCode: 'NA' } },
  { dialCode: 674, country: { name: 'Nauru', isoCode: 'NR' } },
  { dialCode: 977, country: { name: 'Nepal', isoCode: 'NP' } },
  { dialCode: 31, country: { name: 'Netherlands', isoCode: 'NL' } },
  { dialCode: 599, country: { name: 'Netherlands Antilles', isoCode: 'AN' } },
  { dialCode: 687, country: { name: 'New Caledonia', isoCode: 'NC' } },
  { dialCode: 64, country: { name: 'New Zealand', isoCode: 'NZ' } },
  { dialCode: 505, country: { name: 'Nicaragua', isoCode: 'NI' } },
  { dialCode: 227, country: { name: 'Niger', isoCode: 'NE' } },
  { dialCode: 234, country: { name: 'Nigeria', isoCode: 'NG' } },
  { dialCode: 683, country: { name: 'Niue', isoCode: 'NU' } },
  { dialCode: 672, country: { name: 'Norfolk Island', isoCode: 'NF' } },
  { dialCode: 389, country: { name: 'North Macedonia', isoCode: 'MK' } },
  {
    dialCode: 1670,
    country: { name: 'Northern Mariana Islands', isoCode: 'MP' },
  },
  { dialCode: 47, country: { name: 'Norway', isoCode: 'NO' } },
  { dialCode: 968, country: { name: 'Oman', isoCode: 'OM' } },
  { dialCode: 92, country: { name: 'Pakistan', isoCode: 'PK' } },
  { dialCode: 680, country: { name: 'Palau', isoCode: 'PW' } },
  { dialCode: 970, country: { name: 'Palestine', isoCode: 'PS' } },
  { dialCode: 507, country: { name: 'Panama', isoCode: 'PA' } },
  { dialCode: 675, country: { name: 'Papua New Guinea', isoCode: 'PG' } },
  { dialCode: 595, country: { name: 'Paraguay', isoCode: 'PY' } },
  { dialCode: 51, country: { name: 'Peru', isoCode: 'PE' } },
  { dialCode: 63, country: { name: 'Philippines', isoCode: 'PH' } },
  { dialCode: 872, country: { name: 'Pitcairn', isoCode: 'PN' } },
  { dialCode: 48, country: { name: 'Poland', isoCode: 'PL' } },
  { dialCode: 351, country: { name: 'Portugal', isoCode: 'PT' } },
  { dialCode: 1939, country: { name: 'Puerto Rico', isoCode: 'PR' } },
  { dialCode: 974, country: { name: 'Qatar', isoCode: 'QA' } },
  { dialCode: 262, country: { name: 'Reunion', isoCode: 'RE' } },
  { dialCode: 40, country: { name: 'Romania', isoCode: 'RO' } },
  { dialCode: 7, country: { name: 'Russia', isoCode: 'RU' } },
  { dialCode: 250, country: { name: 'Rwanda', isoCode: 'RW' } },
  { dialCode: 590, country: { name: 'Saint Barthelemy', isoCode: 'BL' } },
  {
    dialCode: 290,
    country: {
      name: 'Saint Helena, Ascension and Tristan Da Cunha',
      isoCode: 'SH',
    },
  },
  { dialCode: 1869, country: { name: 'Saint Kitts and Nevis', isoCode: 'KN' } },
  { dialCode: 1758, country: { name: 'Saint Lucia', isoCode: 'LC' } },
  { dialCode: 590, country: { name: 'Saint Martin', isoCode: 'MF' } },
  {
    dialCode: 508,
    country: { name: 'Saint Pierre and Miquelon', isoCode: 'PM' },
  },
  {
    dialCode: 1784,
    country: { name: 'Saint Vincent and the Grenadines', isoCode: 'VC' },
  },
  { dialCode: 685, country: { name: 'Samoa', isoCode: 'WS' } },
  { dialCode: 378, country: { name: 'San Marino', isoCode: 'SM' } },
  { dialCode: 239, country: { name: 'Sao Tome and Principe', isoCode: 'ST' } },
  { dialCode: 966, country: { name: 'Saudi Arabia', isoCode: 'SA' } },
  { dialCode: 221, country: { name: 'Senegal', isoCode: 'SN' } },
  { dialCode: 381, country: { name: 'Serbia', isoCode: 'RS' } },
  { dialCode: 248, country: { name: 'Seychelles', isoCode: 'SC' } },
  { dialCode: 232, country: { name: 'Sierra Leone', isoCode: 'SL' } },
  { dialCode: 65, country: { name: 'Singapore', isoCode: 'SG' } },
  { dialCode: 1721, country: { name: 'Sint Maarten', isoCode: 'SX' } },
  { dialCode: 421, country: { name: 'Slovakia', isoCode: 'SK' } },
  { dialCode: 386, country: { name: 'Slovenia', isoCode: 'SI' } },
  { dialCode: 677, country: { name: 'Solomon Islands', isoCode: 'SB' } },
  { dialCode: 252, country: { name: 'Somalia', isoCode: 'SO' } },
  { dialCode: 27, country: { name: 'South Africa', isoCode: 'ZA' } },
  {
    dialCode: 500,
    country: {
      name: 'South Georgia and the South Sandwich Islands',
      isoCode: 'GS',
    },
  },
  { dialCode: 211, country: { name: 'South Sudan', isoCode: 'SS' } },
  { dialCode: 34, country: { name: 'Spain', isoCode: 'ES' } },
  { dialCode: 94, country: { name: 'Sri Lanka', isoCode: 'LK' } },
  { dialCode: 249, country: { name: 'Sudan', isoCode: 'SD' } },
  { dialCode: 597, country: { name: 'Suriname', isoCode: 'SR' } },
  { dialCode: 47, country: { name: 'Svalbard and Jan Mayen', isoCode: 'SJ' } },
  { dialCode: 46, country: { name: 'Sweden', isoCode: 'SE' } },
  { dialCode: 41, country: { name: 'Switzerland', isoCode: 'CH' } },
  { dialCode: 963, country: { name: 'Syrian Arab Republic', isoCode: 'SY' } },
  { dialCode: 886, country: { name: 'Taiwan', isoCode: 'TW' } },
  { dialCode: 992, country: { name: 'Tajikistan', isoCode: 'TJ' } },
  {
    dialCode: 255,
    country: { name: 'Tanzania, United Republic of Tanzania', isoCode: 'TZ' },
  },
  { dialCode: 66, country: { name: 'Thailand', isoCode: 'TH' } },
  { dialCode: 670, country: { name: 'Timor-Leste', isoCode: 'TL' } },
  { dialCode: 228, country: { name: 'Togo', isoCode: 'TG' } },
  { dialCode: 690, country: { name: 'Tokelau', isoCode: 'TK' } },
  { dialCode: 676, country: { name: 'Tonga', isoCode: 'TO' } },
  { dialCode: 1868, country: { name: 'Trinidad and Tobago', isoCode: 'TT' } },
  { dialCode: 216, country: { name: 'Tunisia', isoCode: 'TN' } },
  { dialCode: 90, country: { name: 'Turkey', isoCode: 'TR' } },
  { dialCode: 993, country: { name: 'Turkmenistan', isoCode: 'TM' } },
  {
    dialCode: 1649,
    country: { name: 'Turks and Caicos Islands', isoCode: 'TC' },
  },
  { dialCode: 688, country: { name: 'Tuvalu', isoCode: 'TV' } },
  { dialCode: 256, country: { name: 'Uganda', isoCode: 'UG' } },
  { dialCode: 380, country: { name: 'Ukraine', isoCode: 'UA' } },
  { dialCode: 971, country: { name: 'United Arab Emirates', isoCode: 'AE' } },
  { dialCode: 44, country: { name: 'United Kingdom', isoCode: 'GB' } },
  { dialCode: 1, country: { name: 'United States', isoCode: 'US' } },
  { dialCode: 598, country: { name: 'Uruguay', isoCode: 'UY' } },
  { dialCode: 998, country: { name: 'Uzbekistan', isoCode: 'UZ' } },
  { dialCode: 678, country: { name: 'Vanuatu', isoCode: 'VU' } },
  {
    dialCode: 58,
    country: {
      name: 'Venezuela, Bolivarian Republic of Venezuela',
      isoCode: 'VE',
    },
  },
  { dialCode: 84, country: { name: 'Vietnam', isoCode: 'VN' } },
  {
    dialCode: 1284,
    country: { name: 'Virgin Islands, British', isoCode: 'VG' },
  },
  { dialCode: 1340, country: { name: 'Virgin Islands, U.S.', isoCode: 'VI' } },
  { dialCode: 681, country: { name: 'Wallis and Futuna', isoCode: 'WF' } },
  { dialCode: 967, country: { name: 'Yemen', isoCode: 'YE' } },
  { dialCode: 260, country: { name: 'Zambia', isoCode: 'ZM' } },
  { dialCode: 263, country: { name: 'Zimbabwe', isoCode: 'ZW' } },
];
